AWSTemplateFormatVersion: 2010-09-09T00:00:00.000Z
Transform: AWS::Serverless-2016-10-31
Description: Serverless REST API for image resizing
Parameters:
  imageBucket:
    Type: String
    Description: S3 Bucket where original images are placed
Resources:
  functionA83DF86C:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-functionA83DF86C
      Description: !Sub
        - Stackery Stack ${StackeryStackTagName} Environment ${StackeryEnvironmentTagName} Function ${ResourceName}
        - ResourceName: functionA83DF86C
      CodeUri: src/functionA83DF86C
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3006
      Events:
        objectStore696A93B3:
          Type: S3
          Properties:
            Bucket: !Ref ${sourceId}
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*
  objectStore696A93B3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-objectStore696A93B3